name: package

on:
  push:
    branches:    
      - master
    tags:
      - v*

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: release
      shell: bash
      run: |
        ls -la
        python CreatePackage.py
    - uses: actions/upload-artifact@v1
      with:
        name: EffekseerForCocos2d-x162d
        path: EffekseerForCocos2d-x
